PRIM( 0x0 , "ABORT", { goto abort; } , { } )
PRIM( 0x1 , "HALT", { goto halt; } , { } )
PRIM( 0x2 , "EXIT", { iptr = rpop; } , { rget( 1 ); } )
PRIM( 0x3 , "EXECUTE", { rpsh = iptr; iptr = dpop; } , { rput( 1 ); dget( 1 ); } )
PRIM( 0x4 , "@RP", { x = rptr; dpsh = x; } , { dput( 1 ); } )
PRIM( 0x5 , "@RB", { x = rbot; dpsh = x; } , { dput( 1 ); } )
PRIM( 0x6 , "@RT", { x = rtop; dpsh = x; } , { dput( 1 ); } )
PRIM( 0x7 , "!RP", { x = dpop; rptr = x; rchk; } , { dget( 1 ); } )
PRIM( 0x8 , "!RB", { x = dpop; rbot = x; rchk; } , { dget( 1 ); } )
PRIM( 0x9 , "!RT", { x = dpop; rtop = x; rchk; } , { dget( 1 ); } )
PRIM( 0xA , "@DP", { x = dptr; dpsh = x; } , { dput( 1 ); } )
PRIM( 0xB , "@DB", { x = dbot; dpsh = x; } , { dput( 1 ); } )
PRIM( 0xC , "@DT", { x = dtop; dpsh = x; } , { dput( 1 ); } )
PRIM( 0xD , "!DP", { x = dpop; dptr = x; dchk; } , { dget( 1 ); } )
PRIM( 0xE , "!DB", { x = dpop; dbot = x; dchk; } , { dget( 1 ); } )
PRIM( 0xF , "!DT", { x = dpop; dtop = x; dchk; } , { dget( 1 ); } )
PRIM( 0x10 , "DROP", { x = dpop; } , { dget( 1 ); } )
PRIM( 0x11 , "DUP", { x = dpop; dpsh = x; dpsh = x; } , { dget( 1 ); dput( 1 ); } )
PRIM( 0x12 , "NIP", { y = dpop; x = dpop; dpsh = y; } , { dget( 2 ); } )
PRIM( 0x13 , "SWAP", { y = dpop; x = dpop; dpsh = y; dpsh = x; } , { dget( 2 ); } )
PRIM( 0x14 , "OVER", { y = dpop; x = dpop; dpsh = x; dpsh = y; dpsh = x; } , { dget( 2 ); dput( 1 ); } )
PRIM( 0x15 , "TUCK", { y = dpop; x = dpop; dpsh = y; dpsh = x; dpsh = y; } , { dget( 2 ); dput( 1 ); } )
PRIM( 0x16 , "ROT", { z = dpop; y = dpop; x = dpop; dpsh = y; dpsh = z; dpsh = x; } , { dget( 3 ); } )
PRIM( 0x17 , "TOR", { z = dpop; y = dpop; x = dpop; dpsh = z; dpsh = x; dpsh = y; } , { dget( 3 ); } )
