PRIM( ABORT, goto abort; , ; )
PRIM( HALT, goto halt; , ; )
PRIM( EXIT, iptr = rpop; , rget( 1 ); ; )
PRIM( EXECUTE, rpsh = iptr; iptr = dpop; , rput( 1 ); dget( 1 ); ; )
PRIM( FETCHRP, x = rptr; dpsh = x; , dput( 1 ); ; )
PRIM( FETCHRB, x = rbot; dpsh = x; , dput( 1 ); ; )
PRIM( FETCHRT, x = rtop; dpsh = x; , dput( 1 ); ; )
PRIM( STORERP, x = dpop; rptr = x; rchk; , dget( 1 ); ; )
PRIM( STORERB, x = dpop; rbot = x; rchk; , dget( 1 ); ; )
PRIM( STORERT, x = dpop; rtop = x; rchk; , dget( 1 ); ; )
PRIM( FETCHDP, x = dptr; dpsh = x; , dput( 1 ); ; )
PRIM( FETCHDB, x = dbot; dpsh = x; , dput( 1 ); ; )
PRIM( FETCHDT, x = dtop; dpsh = x; , dput( 1 ); ; )
PRIM( STOREDP, x = dpop; dptr = x; dchk; , dget( 1 ); ; )
PRIM( STOREDB, x = dpop; dbot = x; dchk; , dget( 1 ); ; )
PRIM( STOREDT, x = dpop; dtop = x; dchk; , dget( 1 ); ; )
